//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zfy84Entities : DbContext
    {
        public zfy84Entities()
            : base("name=zfy84Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Device> Devices { get; set; }
        public DbSet<Doc> Docs { get; set; }
        public DbSet<DocDownLoad> DocDownLoads { get; set; }
        public DbSet<DocGrade> DocGrades { get; set; }
        public DbSet<DocPreviewParam> DocPreviewParams { get; set; }
        public DbSet<DocQry> DocQries { get; set; }
        public DbSet<DocQryByCustom> DocQryByCustoms { get; set; }
        public DbSet<DocType> DocTypes { get; set; }
        public DbSet<DocUpLoadSet> DocUpLoadSets { get; set; }
        public DbSet<DocUpLoadSetIP> DocUpLoadSetIPs { get; set; }
        public DbSet<EmailInfo> EmailInfoes { get; set; }
        public DbSet<Note> Notes { get; set; }
        public DbSet<OperateType> OperateTypes { get; set; }
        public DbSet<QryPhotoReadPath> QryPhotoReadPaths { get; set; }
        public DbSet<QryPhotoSavePath> QryPhotoSavePaths { get; set; }
        public DbSet<RightGroup> RightGroups { get; set; }
        public DbSet<RightGroupHa> RightGroupHas { get; set; }
        public DbSet<RightGroupStaffDep> RightGroupStaffDeps { get; set; }
        public DbSet<RightName> RightNames { get; set; }
        public DbSet<SaveCloudSpace> SaveCloudSpaces { get; set; }
        public DbSet<SaveFilePath> SaveFilePaths { get; set; }
        public DbSet<Sequence> Sequences { get; set; }
        public DbSet<Server> Servers { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<StaffDepartment> StaffDepartments { get; set; }
        public DbSet<StaffRight> StaffRights { get; set; }
        public DbSet<StaffRightHa> StaffRightHas { get; set; }
        public DbSet<SysNote> SysNotes { get; set; }
        public DbSet<SysNoteRead> SysNoteReads { get; set; }
        public DbSet<SysRec> SysRecs { get; set; }
        public DbSet<TimingExportExecel> TimingExportExecels { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
        public DbSet<WorkStation> WorkStations { get; set; }
        public DbSet<WorkStationPath> WorkStationPaths { get; set; }
        public DbSet<WorkStationPathInfo> WorkStationPathInfoes { get; set; }
    }
}
