//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc
    {
        public string PolNo { get; set; }
        public string DevNo { get; set; }
        public Nullable<System.DateTime> PicDate { get; set; }
        public Nullable<System.DateTime> UpLoadDate { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<int> DocType { get; set; }
        public string Comment { get; set; }
        public string PrevFile { get; set; }
        public string DestFile { get; set; }
        public string FaceFile { get; set; }
        public string GPSFile { get; set; }
        public string Param { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> IsFinished { get; set; }
        public Nullable<bool> IsSele { get; set; }
        public Nullable<int> WorkStationID { get; set; }
        public Nullable<int> StoreStatus { get; set; }
        public Nullable<long> VideoLength { get; set; }
        public Nullable<long> FileLength { get; set; }
        public string DocNo { get; set; }
        public Nullable<int> IsUpload { get; set; }
        public string UploadIp { get; set; }
        public string UploadPort { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string save_path { get; set; }
        public int id { get; set; }
        public string Location { get; set; }
        public string DocStatus { get; set; }
        public Nullable<int> DocStatusProgress { get; set; }
    }
}
