//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocDownLoad
    {
        public int ID { get; set; }
        public Nullable<int> DocID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> DownLoadTime { get; set; }
        public string ComputerName { get; set; }
        public Nullable<int> DoType { get; set; }
    }
}
