//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGrade
    {
        public int ID { get; set; }
        public string GradeName { get; set; }
        public string GradeEng { get; set; }
        public Nullable<int> DocGrade_Id_Pk { get; set; }
    }
}
