//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocPreviewParam
    {
        public int ID { get; set; }
        public Nullable<int> pImgW { get; set; }
        public Nullable<int> pImgH { get; set; }
        public Nullable<int> vVideoBitrate { get; set; }
        public Nullable<int> vAudioBitrate { get; set; }
        public Nullable<int> vAudioFreq { get; set; }
        public Nullable<int> vImgW { get; set; }
        public Nullable<int> vImgH { get; set; }
        public Nullable<bool> vOriginalSize { get; set; }
        public Nullable<int> aBitrate { get; set; }
        public Nullable<int> aFreq { get; set; }
        public Nullable<int> vPreImgW { get; set; }
        public Nullable<int> vPreImgH { get; set; }
        public Nullable<bool> GenPreview { get; set; }
    }
}
