//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocQry
    {
        public int DocID { get; set; }
        public string PolNo { get; set; }
        public Nullable<int> PolDepartmentID { get; set; }
        public string PolDepartmentName { get; set; }
        public string DevNo { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> PicDate { get; set; }
        public Nullable<System.DateTime> UpLoadDate { get; set; }
        public Nullable<int> GradeID { get; set; }
        public string GradeName { get; set; }
        public string GradeEng { get; set; }
        public Nullable<int> DocTypeID { get; set; }
        public string DocTypeChs { get; set; }
        public string DocTypeEng { get; set; }
        public string Comment { get; set; }
        public string PrevFile { get; set; }
        public string DestFile { get; set; }
        public string FaceFile { get; set; }
        public string GPSFile { get; set; }
        public string Param { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsSele { get; set; }
        public Nullable<int> IsFinished { get; set; }
        public Nullable<int> WorkStationID { get; set; }
        public string WorkStationName { get; set; }
        public string WorkStationIP { get; set; }
        public string WebAdd { get; set; }
        public string VirtualPath { get; set; }
        public Nullable<int> StoreStatus { get; set; }
        public Nullable<long> VideoLength { get; set; }
        public Nullable<long> FileLength { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> LastPicDate { get; set; }
    }
}
