//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocUpLoadSetIP
    {
        public int ID { get; set; }
        public string ServerIP { get; set; }
        public string WorkStationIP { get; set; }
        public string UploadTime { get; set; }
        public Nullable<int> GradeID { get; set; }
    }
}
