//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class RightName
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public Nullable<int> RightType { get; set; }
        public Nullable<int> ShowOrd { get; set; }
        public string SiteUrl { get; set; }
        public Nullable<int> MenuYayer { get; set; }
    }
}
