//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveFilePath
    {
        public int SrcOrder { get; set; }
        public string PathName { get; set; }
        public string VirtualPath { get; set; }
        public Nullable<int> PathType { get; set; }
        public string mmsPath { get; set; }
        public int id { get; set; }
    }
}
