//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDepartment
    {
        public Nullable<int> ParentID { get; set; }
        public string DepartName { get; set; }
        public Nullable<int> ShowOrd { get; set; }
        public Nullable<int> DepartLayer { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public int id { get; set; }
    }
}
