//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID { get; set; }
        public Nullable<short> UserLevel { get; set; }
        public string UserName { get; set; }
        public string LoginName { get; set; }
        public string PassWord { get; set; }
        public string CorpName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string PolNo { get; set; }
        public string DevNo { get; set; }
        public string DevPwd { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Status { get; set; }
    }
}
