//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffRightHa
    {
        public int StaffID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> RightGroupID { get; set; }
        public Nullable<int> RightNameID { get; set; }
        public string RightName { get; set; }
        public Nullable<int> PolDepartmentID { get; set; }
        public string Siteurl { get; set; }
        public Nullable<int> MenuYayer { get; set; }
    }
}
