//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysNoteRead
    {
        public int id { get; set; }
        public int rightnameid { get; set; }
        public int operatetypeid { get; set; }
        public string operatename { get; set; }
        public string englishname { get; set; }
        public System.DateTime operatedate { get; set; }
        public string ipaddr { get; set; }
        public string polno { get; set; }
        public string username { get; set; }
        public string rightName { get; set; }
        public string rightNameEng { get; set; }
    }
}
