//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysNote
    {
        public int ID { get; set; }
        public int RightNameID { get; set; }
        public int OperateTypeID { get; set; }
        public System.DateTime OperateDate { get; set; }
        public string IpAddr { get; set; }
        public int StaffID { get; set; }
    }
}
