//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkStationPath
    {
        public int ID { get; set; }
        public Nullable<int> WorkStationID { get; set; }
        public string StorePath { get; set; }
        public string VirtualPath { get; set; }
        public Nullable<int> Ord { get; set; }
    }
}
