//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkStation
    {
        public string WorkStationname { get; set; }
        public string WorkStationIP { get; set; }
        public string WebAdd { get; set; }
        public Nullable<int> SaveDays { get; set; }
        public Nullable<int> StationType { get; set; }
        public string StorePath { get; set; }
        public string VirtualPath { get; set; }
        public int id { get; set; }
    }
}
